dist: trusty
sudo: true
language: csharp
solution: AppIFES.sln
 
jdk:
 - oraclejdk8

addons:
  sonarqube:
    organization: "devweb-ifes2017-github"
    token:
      secure: "$SONAR_TOKEN"

branches:
  only:
    - master
    - v0100  
script:
  - sonar-scanner 
  
